/**
 * i18n.js — runtime i18n for the landing page.
 *
 * Reads window.I18N_TRANSLATIONS (provided by i18n.translations.js, which is
 * generated by translate-build.js from i18n.source.json + i18n.overrides.json).
 *
 * Behavior:
 *   - On first visit, picks the language from localStorage if present, else
 *     falls back to navigator.language (only if it's one of the supported
 *     codes), else EN.
 *   - Subsequent visits reuse the saved choice.
 *   - Switching language: instant DOM swap, persists to localStorage, fires a
 *     `i18n:change` CustomEvent on document.
 *   - Optional: ask the MyMemory API on demand for any missing key, then cache
 *     the result in localStorage with a TTL of 30 days. Falls back to EN if
 *     the API is unreachable.
 *
 * Markup contract:
 *   <span data-i18n="hero.title">Default English</span>
 *   <a data-i18n-aria="nav.openMenu" aria-label="Open menu">☰</a>
 *   <span data-i18n-html="<b>welcome</b>">…</span>  (only when HTML is intentional)
 */

(function () {
  'use strict';

  const STORAGE_KEY = 'mfa.lang';
  const CACHE_KEY = 'mfa.lang.cache';
  const CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
  const SUPPORTED = ['en', 'es', 'pt'];
  const DEFAULT_LANG = 'en';
  const HTML = document.documentElement;

  const dictionaries = (window.I18N_TRANSLATIONS) || { en: {} };
  let current = DEFAULT_LANG;

  function getSaved() {
    try {
      const v = localStorage.getItem(STORAGE_KEY);
      if (v && SUPPORTED.includes(v)) return v;
    } catch (e) {
      /* private mode / disabled storage */
    }
    return null;
  }

  function save(lang) {
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch (e) {
      /* ignore */
    }
  }

  function detect() {
    const saved = getSaved();
    if (saved) return saved;
    const nav = (navigator.language || navigator.userLanguage || DEFAULT_LANG)
      .toLowerCase()
      .slice(0, 2);
    return SUPPORTED.includes(nav) ? nav : DEFAULT_LANG;
  }

  function getDict(lang) {
    return dictionaries[lang] || dictionaries[DEFAULT_LANG] || {};
  }

  function setText(selector, attr, key) {
    const el = document.querySelector(selector);
    if (!el) return;
    const dict = getDict(current);
    if (dict[key] !== undefined) el[attr] = dict[key];
  }

  function applyAll() {
    const dict = getDict(current);

    document.querySelectorAll('[data-i18n]').forEach((el) => {
      const key = el.getAttribute('data-i18n');
      if (dict[key] !== undefined) el.textContent = dict[key];
    });

    document.querySelectorAll('[data-i18n-aria]').forEach((el) => {
      const key = el.getAttribute('data-i18n-aria');
      if (dict[key] !== undefined) el.setAttribute('aria-label', dict[key]);
    });

    document.querySelectorAll('[data-i18n-title]').forEach((el) => {
      const key = el.getAttribute('data-i18n-title');
      if (dict[key] !== undefined) el.setAttribute('title', dict[key]);
    });

    HTML.setAttribute('lang', current);
    HTML.setAttribute('data-lang', current);

    document.querySelectorAll('[data-lang-switch]').forEach((btn) => {
      const isActive = btn.getAttribute('data-lang-switch') === current;
      btn.classList.toggle('is-active', isActive);
      btn.setAttribute('aria-pressed', String(isActive));
    });

    // Reflect on the dropdown trigger label
    const trigger = document.querySelector('.lang-trigger');
    if (trigger) {
      const label = trigger.querySelector('.lang-current');
      if (label) label.textContent = current.toUpperCase();
    }

    // Mobile menu aria-label swap when open/closed
    const navToggle = document.getElementById('navToggle');
    if (navToggle) {
      const isOpen = navToggle.getAttribute('aria-expanded') === 'true';
      const key = isOpen ? 'nav.closeMenu' : 'nav.openMenu';
      if (dict[key]) navToggle.setAttribute('aria-label', dict[key]);
    }
  }

  function setLang(lang, opts) {
    if (!SUPPORTED.includes(lang)) return;
    current = lang;
    save(lang);
    applyAll();
    if (!opts || !opts.silent) {
      document.dispatchEvent(new CustomEvent('i18n:change', { detail: { lang } }));
    }
  }

  /* ----------------------------------------------------------------------
   * Optional on-demand translation: if a key is missing in the current
   * dictionary, ask MyMemory to translate the English fallback and cache
   * the result. Fully off by default (turns into a normal EN fallback).
   * Enable with window.I18N_LIVE = true before this script runs.
   * --------------------------------------------------------------------- */
  function getCache() {
    try {
      return JSON.parse(localStorage.getItem(CACHE_KEY) || '{}');
    } catch (e) {
      return {};
    }
  }

  function setCache(cache) {
    try {
      localStorage.setItem(CACHE_KEY, JSON.stringify(cache));
    } catch (e) {
      /* ignore */
    }
  }

  async function fillMissingKey(key, target) {
    const fallback = dictionaries.en[key];
    if (!fallback) return null;

    const cache = getCache();
    const cached = cache[target] && cache[target][key];
    if (cached && Date.now() - cached.ts < CACHE_TTL_MS) {
      return cached.value;
    }

    const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(fallback)}&langpair=en|${target}&de=matheusfabio13@hotmail.com`;
    try {
      const res = await fetch(url, { mode: 'cors' });
      if (!res.ok) return null;
      const json = await res.json();
      const translated = json.responseData && json.responseData.translatedText;
      if (!translated) return null;
      cache[target] = cache[target] || {};
      cache[target][key] = { value: translated, ts: Date.now() };
      setCache(cache);
      return translated;
    } catch (e) {
      return null;
    }
  }

  async function ensureKey(key) {
    if (key in dictionaries[current]) return;
    const fetched = await fillMissingKey(key, current);
    if (fetched) {
      dictionaries[current] = dictionaries[current] || {};
      dictionaries[current][key] = fetched;
      applyAll();
    }
  }

  /* ----------------------------------------------------------------------
   * Public API
   * --------------------------------------------------------------------- */
  window.I18N = {
    supported: SUPPORTED.slice(),
    current: () => current,
    set: setLang,
    apply: applyAll,
    ensure: ensureKey,
    t: (key) => getDict(current)[key] || dictionaries.en[key] || key,
  };

  /* ----------------------------------------------------------------------
   * Boot
   * --------------------------------------------------------------------- */
  function boot() {
    current = detect();
    applyAll();

    // Dropdown toggle
    const dropdown = document.querySelector('.lang-dropdown');
    const trigger = dropdown && dropdown.querySelector('.lang-trigger');
    const menu = dropdown && dropdown.querySelector('.lang-menu');

    function closeMenu() {
      if (!dropdown) return;
      dropdown.classList.remove('is-open');
      if (trigger) trigger.setAttribute('aria-expanded', 'false');
      if (menu) menu.setAttribute('aria-hidden', 'true');
      document.removeEventListener('click', onDocClick);
      document.removeEventListener('keydown', onKey);
    }

    function openMenu() {
      if (!dropdown) return;
      dropdown.classList.add('is-open');
      if (trigger) trigger.setAttribute('aria-expanded', 'true');
      if (menu) menu.setAttribute('aria-hidden', 'false');
      // Defer to next tick so the click that opened it doesn't immediately close
      setTimeout(() => {
        document.addEventListener('click', onDocClick);
        document.addEventListener('keydown', onKey);
      }, 0);
    }

    function onDocClick(e) {
      if (!dropdown.contains(e.target)) closeMenu();
    }

    function onKey(e) {
      if (e.key === 'Escape') closeMenu();
    }

    if (trigger) {
      trigger.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        if (dropdown.classList.contains('is-open')) closeMenu();
        else openMenu();
      });
    }

    document.querySelectorAll('[data-lang-switch]').forEach((btn) => {
      btn.addEventListener('click', (e) => {
        e.preventDefault();
        const next = btn.getAttribute('data-lang-switch');
        setLang(next);
        closeMenu();
      });
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
