/**
 * translate-build.js
 *
 * Generates i18n.translations.js by calling the MyMemory translation API
 * (free, no key required) for each string in i18n.source.json.
 *
 * Usage:  node translate-build.js
 * Output: i18n.translations.js
 *
 * Demo: shows API integration, async batching, retry, and graceful fallbacks
 * — useful as a portfolio talking point for an AI Engineer.
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const SOURCE_FILE = path.join(__dirname, 'i18n.source.json');
const OVERRIDES_FILE = path.join(__dirname, 'i18n.overrides.json');
const OUTPUT_FILE = path.join(__dirname, 'i18n.translations.js');
const TARGETS = ['es', 'pt'];
const SOURCE_LANG = 'en';
const BATCH_SIZE = 4;       // concurrent requests
const BATCH_DELAY_MS = 250; // politeness delay between batches
const MAX_RETRIES = 2;
const TIMEOUT_MS = 10000;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function translateOnce(text, target) {
  const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${SOURCE_LANG}|${target}&de=matheusfabio13@hotmail.com`;
  return new Promise((resolve, reject) => {
    const req = https.get(url, { timeout: TIMEOUT_MS }, (res) => {
      let body = '';
      res.on('data', (c) => (body += c));
      res.on('end', () => {
        try {
          const json = JSON.parse(body);
          if (json.responseStatus !== 200 || !json.responseData) {
            return reject(new Error(json.responseDetails || `HTTP ${res.statusCode}`));
          }
          resolve(json.responseData.translatedText || text);
        } catch (e) {
          reject(e);
        }
      });
    });
    req.on('timeout', () => req.destroy(new Error('timeout')));
    req.on('error', reject);
  });
}

async function translate(text, target) {
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const out = await translateOnce(text, target);
      if (out && out.trim().length > 0) return out;
    } catch (e) {
      if (attempt === MAX_RETRIES) {
        console.warn(`  [warn] failed "${text.slice(0, 40)}…" → ${target}: ${e.message}`);
        return text; // graceful fallback: keep the English source
      }
      await sleep(400 * (attempt + 1));
    }
  }
  return text;
}

async function runBatched(items, target) {
  const out = {};
  for (let i = 0; i < items.length; i += BATCH_SIZE) {
    const batch = items.slice(i, i + BATCH_SIZE);
    const results = await Promise.all(
      batch.map(async ([key, value]) => {
        const translated = await translate(value, target);
        return [key, translated];
      })
    );
    for (const [k, v] of results) out[k] = v;
    process.stdout.write(`  ${target}: ${Math.min(i + BATCH_SIZE, items.length)}/${items.length}\r`);
    if (i + BATCH_SIZE < items.length) await sleep(BATCH_DELAY_MS);
  }
  process.stdout.write('\n');
  return out;
}

async function main() {
  if (!fs.existsSync(SOURCE_FILE)) {
    console.error(`Source file not found: ${SOURCE_FILE}`);
    process.exit(1);
  }
  const source = JSON.parse(fs.readFileSync(SOURCE_FILE, 'utf8'));
  const entries = Object.entries(source);

  console.log(`Translating ${entries.length} strings → ${TARGETS.join(', ')} via MyMemory…\n`);

  const result = { en: source };
  for (const target of TARGETS) {
    console.log(`[${target}]`);
    result[target] = await runBatched(entries, target);
  }

  // Sanity check: every key must exist in every language
  for (const target of TARGETS) {
    for (const [key] of entries) {
      if (!(key in result[target])) {
        console.warn(`[warn] missing ${target}.${key}, falling back to EN`);
        result[target][key] = source[key];
      }
    }
  }

  // Apply manual overrides (post-edits to fix machine-translation errors)
  if (fs.existsSync(OVERRIDES_FILE)) {
    const overrides = JSON.parse(fs.readFileSync(OVERRIDES_FILE, 'utf8'));
    let overrideCount = 0;
    for (const target of TARGETS) {
      if (!overrides[target]) continue;
      for (const [key, value] of Object.entries(overrides[target])) {
        if (key.startsWith('_')) continue; // comment keys
        if (key in result[target]) {
          result[target][key] = value;
          overrideCount++;
        }
      }
    }
    if (overrideCount > 0) {
      console.log(`Applied ${overrideCount} manual override(s) from i18n.overrides.json`);
    }
  }

  const banner = [
    '/**',
    ' * i18n.translations.js',
    ' * Auto-generated by translate-build.js via MyMemory API.',
    ' * Do not edit by hand — re-run `node translate-build.js` to refresh.',
    ` * Generated: ${new Date().toISOString()}`,
    ' */',
  ].join('\n');

  const js =
    banner +
    '\nwindow.I18N_TRANSLATIONS = ' +
    JSON.stringify(result, null, 2) +
    ';\n';

  fs.writeFileSync(OUTPUT_FILE, js, 'utf8');
  console.log(`\nWrote ${OUTPUT_FILE} (${(js.length / 1024).toFixed(1)} KB)`);
  console.log(`Languages: ${Object.keys(result).join(', ')} · Strings: ${entries.length}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
